package ui

import (
	"fmt"
	"strings"
	"time"

	"github.com/tarek-k-devs/devsweep/internal/store"
)

// PrintReport displays the trend report.
func PrintReport(kills []store.KillStat, orphans []store.OrphanStat, portConflicts int, days int) {
	fmt.Printf("  📊 DevSweep Report (last %d days)\n\n", days)

	// Kill summary
	totalKilled := 0
	var totalMem float64
	for _, k := range kills {
		totalKilled += k.Count
		totalMem += k.TotalMem
	}

	if totalKilled == 0 && len(orphans) == 0 {
		fmt.Println("  No activity recorded yet. Run `devsweep watch start` to begin tracking.")
		return
	}

	fmt.Printf("  Processes killed:       %d\n", totalKilled)
	fmt.Printf("  RAM reclaimed:          %.1f MB total\n", totalMem)
	fmt.Printf("  Port conflicts:         %d times\n", portConflicts)

	if len(kills) > 0 {
		fmt.Printf("  Top offender:           %s — %d killed\n", kills[0].Tool, kills[0].Count)
	}

	// Orphan table
	if len(orphans) > 0 {
		fmt.Println()
		fmt.Println("  🔗 Orphans by Parent Tool:")
		fmt.Println("  ┌──────────────────────┬─────────────┬───────────────┐")
		fmt.Println("  │ Tool                 │ Orphans Left│ RAM Wasted    │")
		fmt.Println("  ├──────────────────────┼─────────────┼───────────────┤")
		for _, o := range orphans {
			name := o.ParentTool
			if len(name) > 20 {
				name = name[:17] + "..."
			}
			fmt.Printf("  │ %-20s │ %-11d │ %8.0f MB   │\n", name, o.OrphanCount, o.TotalMemMB)
		}
		fmt.Println("  └──────────────────────┴─────────────┴───────────────┘")
	}

	fmt.Println()
}

// GenerateExport creates a Markdown report for a specific tool.
func GenerateExport(toolName string, orphans []store.OrphanStat, kills []store.KillStat, days int) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("## DevSweep: Process Cleanup Report for %s\n\n", toolName))
	sb.WriteString(fmt.Sprintf("**Period:** Last %d days (as of %s)\n\n", days, time.Now().Format("January 2, 2006")))

	// Find stats for this tool
	var toolOrphans *store.OrphanStat
	for _, o := range orphans {
		if strings.EqualFold(o.ParentTool, toolName) {
			toolOrphans = &o
			break
		}
	}

	var toolKills *store.KillStat
	for _, k := range kills {
		if strings.EqualFold(k.Tool, toolName) {
			toolKills = &k
			break
		}
	}

	if toolOrphans != nil {
		sb.WriteString(fmt.Sprintf("%s left **%d orphaned processes**:\n\n", toolName, toolOrphans.OrphanCount))
		sb.WriteString(fmt.Sprintf("**Total RAM wasted:** %.0f MB\n\n", toolOrphans.TotalMemMB))
	}

	if toolKills != nil {
		sb.WriteString(fmt.Sprintf("**Processes killed:** %d (%.0f MB reclaimed)\n\n", toolKills.Count, toolKills.TotalMem))
	}

	if toolOrphans == nil && toolKills == nil {
		sb.WriteString(fmt.Sprintf("No data found for \"%s\" in the last %d days.\n\n", toolName, days))
	}

	sb.WriteString("**Suggested fix:** Send SIGTERM to child process group on CLI exit.\n\n")
	sb.WriteString("_Generated by [DevSweep](https://github.com/tarek-k-devs/devsweep)_\n")

	return sb.String()
}
